### PR TITLE
add zulily and GenUI to list of Seattle companies who employ PHP developers

### PR DESCRIPTION
**Pull request by bfellows37**

### CODE REVIEW

**Comment by cookieguru** [comment]
Talking to a recruiter just now there's only 1 team left at Zulily that still uses PHP, and they're in the process of porting that over to Java to match the rest of their stack.

**Comment by bfellows37** [comment]
I am on one of the more-than-one teams who use PHP. I don't think it is going away tomorrow.

**Comment by bfellows37** [comment]
Hey, we're digging the PHP hole deeper at Zulily. I think we should merge this and help them out.

**Comment by andrewwoods** [comment]
Thanks for reminding me about this. Glad to hear they're using more PHP

**Pull request merged**
